parameters:

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Configuration du LoginListener pour écouter les événements de connexion et de déconnexion
    App\EventListener\LoginListener:
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onSecurityInteractiveLogin' }
            - { name: 'kernel.event_listener', event: 'security.logout', method: 'onLogout' }

    # Configuration de ScategorieListener pour écouter l'événement prePersist
    App\EventListener\ScategorieListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
